### 1. Write a Python Program to Add Two Matrices?

In [42]:
import numpy as np

In [43]:
x = np.array([[12,7,3],
              [4,5,6],
              [7,8,9]])
y = np.array([[5,8,1],
              [6,7,3],
              [4,5,9]])
x+y

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

### 2. Write a Python Program to Multiply Two Matrices?


In [44]:
x =([[12,7,3],[4,5,6],[7,8,9]])
y = ([[5,8,1],[6,7,3],[4,5,9]])
z = np.dot(x,y)
print(z)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


### 3. Write a Python Program to Transpose a Matrix?

In [54]:
x =([[12,7,3],
     [4,5,6],
     [7,8,9]])

y = np.zeros((3,3))

for i in range(len(x)):
    for j in range(len(x[0])):
        y[j][i]= x[i][j]
        
print(y)
    

[[12.  4.  7.]
 [ 7.  5.  8.]
 [ 3.  6.  9.]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [93]:
def sortwords(s):
    '''Enter a string'''
    w = [words.lower() for words in s.split()]
    w.sort()
    return w

In [94]:
sortwords("I love chocholates")

['chocholates', 'i', 'love']

### 5. Write a Python Program to Remove Punctuation From a String?

In [107]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

s = "Hello!!!..., How are you???."

no_punct = ""
for char in s:
    if char not in punctuations:
        no_punct = no_punct + char

print(no_punct)

Hello How are you
